### ISSUE TITLE
Does BUILD_MODE override NODE_ENV?

### ISSUE THREAD

**Issue by phcoliveira** [asika32764/vue-cli-plugin-node-env#1]
https://github.com/asika32764/vue-cli-plugin-node-env/blob/f1b0dd759b00cbb742da70330b3b770c693d7efe/index.js#L13

Hello there!

I was wondering about the line above. It seems that it possible to use `BUILD_MODE` as `production` and `NODE_ENV` as `staging`, for example. But doesn't the variable `BUILD_MODE` override `NODE_ENV`?

**Comment by asika32764** [comment]
Yes, the BUILD_MODE will override NODE_ENV , since Vue will load env.{NODE_ENV} first.

For example
`NODE_ENV=staging BUILD_MODE=production`

Will load `.env.staging` file, but build webpack with production mode.
